version: "3.8"

services:

  server:
    container_name: server
    build: server/
    environment:
      - SERVER_ID=server-1
    expose:
      - "4000"
    networks:
      - app-network


  load_balancer:
    container_name: load_balancer
    build: load_balancer/
    ports:
      - "5000:5000"
    networks:
      - app-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true

  
networks:
  app-network:
    name: "app-network"
    driver: bridge
